//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.30 at 10:48:50 AM IST 
//


package org.ofbiz.party.test.webservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="RESPONSE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RESP_COUPON_DETAILS" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RESP_COUPON_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RESP_TRANSACTOIN_DETAILS" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RESP_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="RESPONSE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ResponseId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "WEBSERVICE")
public class WEBSERVICE {

    @XmlElement(name = "RESPONSE")
    protected List<WEBSERVICE.RESPONSE> response;

    /**
     * Gets the value of the response property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the response property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRESPONSE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WEBSERVICE.RESPONSE }
     * 
     * 
     */
    public List<WEBSERVICE.RESPONSE> getRESPONSE() {
        if (response == null) {
            response = new ArrayList<WEBSERVICE.RESPONSE>();
        }
        return this.response;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RESP_COUPON_DETAILS" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RESP_COUPON_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RESP_TRANSACTOIN_DETAILS" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RESP_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="RESPONSE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ResponseId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "respcoupondetails",
        "resptransactoindetails"
    })
    public static class RESPONSE {

        @XmlElement(name = "RESP_COUPON_DETAILS")
        protected List<WEBSERVICE.RESPONSE.RESPCOUPONDETAILS> respcoupondetails;
        @XmlElement(name = "RESP_TRANSACTOIN_DETAILS")
        protected List<WEBSERVICE.RESPONSE.RESPTRANSACTOINDETAILS> resptransactoindetails;
        @XmlAttribute(name = "ResponseId")
        protected String responseId;

        /**
         * Gets the value of the respcoupondetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the respcoupondetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRESPCOUPONDETAILS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WEBSERVICE.RESPONSE.RESPCOUPONDETAILS }
         * 
         * 
         */
        public List<WEBSERVICE.RESPONSE.RESPCOUPONDETAILS> getRESPCOUPONDETAILS() {
            if (respcoupondetails == null) {
                respcoupondetails = new ArrayList<WEBSERVICE.RESPONSE.RESPCOUPONDETAILS>();
            }
            return this.respcoupondetails;
        }

        /**
         * Gets the value of the resptransactoindetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the resptransactoindetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRESPTRANSACTOINDETAILS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WEBSERVICE.RESPONSE.RESPTRANSACTOINDETAILS }
         * 
         * 
         */
        public List<WEBSERVICE.RESPONSE.RESPTRANSACTOINDETAILS> getRESPTRANSACTOINDETAILS() {
            if (resptransactoindetails == null) {
                resptransactoindetails = new ArrayList<WEBSERVICE.RESPONSE.RESPTRANSACTOINDETAILS>();
            }
            return this.resptransactoindetails;
        }

        /**
         * Gets the value of the responseId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseId() {
            return responseId;
        }

        /**
         * Sets the value of the responseId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseId(String value) {
            this.responseId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RESP_COUPON_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "respcouponcode"
        })
        public static class RESPCOUPONDETAILS {

            @XmlElement(name = "RESP_COUPON_CODE")
            protected String respcouponcode;

            /**
             * Gets the value of the respcouponcode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRESPCOUPONCODE() {
                return respcouponcode;
            }

            /**
             * Sets the value of the respcouponcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRESPCOUPONCODE(String value) {
                this.respcouponcode = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RESP_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="RESPONSE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "respstatuscode",
            "responsecode"
        })
        public static class RESPTRANSACTOINDETAILS {

            @XmlElement(name = "RESP_STATUS_CODE")
            protected String respstatuscode;
            @XmlElement(name = "RESPONSE_CODE")
            protected String responsecode;

            /**
             * Gets the value of the respstatuscode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRESPSTATUSCODE() {
                return respstatuscode;
            }

            /**
             * Sets the value of the respstatuscode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRESPSTATUSCODE(String value) {
                this.respstatuscode = value;
            }

            /**
             * Gets the value of the responsecode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRESPONSECODE() {
                return responsecode;
            }

            /**
             * Sets the value of the responsecode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRESPONSECODE(String value) {
                this.responsecode = value;
            }

        }

    }

}
